version: '3'
services:    
  eureka:
    build: './api/spring-cloud-eureka-server'
    ports:
      - "8761:8761"
    #volumes:
      #- ./app/src:/app/src
    #environment:
      # If a production enviroment is desired, set the APP_ENV variable to production
      # APP_ENV: 'production'
      #APP_ENV: 'development'
    #links:
      #- api

  zuul:
    build: './api/spring-cloud-zuul-gateway-2'
    ports:
        - "8085:8085"
    depends_on:
        - "eureka"
    # api host port defined the same as in the container
    links: 
      - "eureka"
    #environment:
      #MYSQL_ROOT_PASSWORD: 'root'
    #ports:
      #- "3001:3001"
    #volumes:
      #- "./api:/api" 
    
  db:
    # This image exposes the standard MySQL port (3306)
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'activity_tracker'
      MYSQL_USER: 'admin' 
      MYSQL_PASSWORD: 'admin'
    ports:
      - "3333:3306"  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db
    # phpmyadmin port defined to 3002
    ports:
      - "3302:3302"
  
  spring-user:
    build: './api/UserManager'
    depends_on:
      - "eureka"
      - "db"   
    links: 
      - "eureka"
      - "db"  
  
  spring-category:
    build: './api/CategoryManagementSystem'
    depends_on:
      - "eureka"
      - "db"   
    links: 
      - "eureka"
      - "db"
      
  spring-activity:
    build: './api/ActivityManagmentService'
    depends_on:
      - "eureka"
      - "db"   
    links: 
      - "eureka"
      - "db"    